server:
  port: 8085

spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5434/testDb
    username: test
    password: test
    hikari:
      poolName: Hikari
      auto-commit: false